/**
 * @file    s11_events.h
 * @date    2026-09-10
 * @brief   Defines the network events used by the S11 simulator.
 *
 * @details
 * This header provides the common event representation used throughout
 * the S11 Communication & Network Simulator.
 *
 * Events represent significant changes in the runtime state of the
 * communication network, such as link failures, link recovery,
 * jamming, network partitions, and recovery completion.
 *
 * The event representation is shared between the network, topology,
 * failure, monitoring, and logging components.
 */

#ifndef S11_EVENTS_H
#define S11_EVENTS_H

/************************************* Include Part ************************************* */

#include <stdint.h>

#include "s11_common.h"

/************************************* Macros Part ************************************* */

/************************************* User Data Types Part ************************************* */

/**
 * @enum s11_event_type_t
 * @brief Represents the type of a network event.
 *
 * @details
 * The event type identifies the significant state change that occurred
 * within the S11 simulation network.
*/
typedef enum
{
    /**
     * @brief Indicates that a network link has become unavailable.
    */
    S11_EVENT_LINK_DOWN = 0,

    /**
     * @brief Indicates that a previously unavailable network link
     *        has become available again.
    */
    S11_EVENT_LINK_UP,

    /**
     * @brief Indicates that jamming has started on a network link.
    */
    S11_EVENT_JAMMING_STARTED,

    /**
     * @brief Indicates that jamming has stopped on a network link.
    */
    S11_EVENT_JAMMING_STOPPED,

    /**
     * @brief Indicates that a network partition has been created.
    */
    S11_EVENT_PARTITION_CREATED,

    /**
     * @brief Indicates that a previously created network partition
     *        has been recovered.
     */
    S11_EVENT_PARTITION_RECOVERED,

    /**
     * @brief Indicates that the network recovery process has completed.
     */
    S11_EVENT_RECOVERY_COMPLETE

} s11_event_type_t;


/**
 * @struct s11_event_t
 * @brief Represents a significant event in the S11 simulation network.
 *
 * @details
 * An event records a change in the runtime state of the simulated
 * communication network.
 *
 * The event can be generated by topology or failure-management
 * components and consumed by monitoring and logging components.
*/
typedef struct
{
    /**
     * @brief Simulation time when the event occurred.
     *
     * @note
     * The timestamp is expressed in microseconds and represents
     * simulation time rather than wall-clock time.
     */
    uint64_t timestamp_us;

    /**
     * @brief Type of the network event.
     */
    s11_event_type_t type;

    /**
     * @brief Identifier of the first node associated with the event.
     *
     * @details
     * For link-related events, this represents one endpoint of the
     * affected network link.
     */
    char node_a[S11_NODE_ID_MAX_LEN];

    /**
     * @brief Identifier of the second node associated with the event.
     *
     * @details
     * For link-related events, this represents the other endpoint of
     * the affected network link.
     */
    char node_b[S11_NODE_ID_MAX_LEN];

} s11_event_t;


/************************************* Function Prototypes Part ************************************* */

/************************************* End of File ************************************* */

#endif /* S11_EVENTS_H */

